title: Experimentaci√≥n Online
description: Data for better products
url: "https://experimentacion-online.github.io"
baseurl: ""
remote_theme: just-the-docs/just-the-docs@v0.9.0
plugins: [jekyll-remote-theme]
search_enabled: true
